# MySQL.  Versions 5.0+ are recommended.
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: dommondba
  password: ch4ng3m£
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: DomMon
